import React, { useState, useEffect } from 'react';
import { ArrowRight, Dice5, ChevronLeft, ChevronRight } from 'lucide-react';
import { INITIAL_ENV_ASSETS, getRandomEnvIndex, EnvironmentCategory } from '../environmentAssets';
import { formatXml } from '../utils/formatUtils';

interface EnvironmentConstructorProps {
  onGenerate: (svgCode: string) => void;
}

const EnvironmentConstructor: React.FC<EnvironmentConstructorProps> = ({ onGenerate }) => {
  const [assets] = useState(INITIAL_ENV_ASSETS);
  
  const [config, setConfig] = useState<Record<EnvironmentCategory, number>>({
    ground: 0,
    main: 0,
    detail: 0,
    shadow: 1, 
  });

  const [previewSvg, setPreviewSvg] = useState('');

  useEffect(() => {
    setPreviewSvg(buildSvg());
  }, [config, assets]);

  const buildSvg = () => {
    const getPart = (key: EnvironmentCategory) => assets[key][config[key]] || assets[key][0];

    const ground = getPart('ground');
    const main = getPart('main');
    const detail = getPart('detail');
    const shadow = getPart('shadow');

    // Increased ViewBox to allow tall trees and shadows without clipping
    return `<svg width="200" height="200" viewBox="-50 -50 300 300" xmlns="http://www.w3.org/2000/svg">
  <!-- Environment Asset Generated by SVG Studio Pro -->
  <g id="ground">${ground.svg}</g>
  <g id="shadow">${shadow.svg}</g>
  <g id="main">${main.svg}</g>
  <g id="detail">${detail.svg}</g>
</svg>`;
  };

  const handleRandomize = () => {
    setConfig({
      ground: getRandomEnvIndex(assets.ground.length),
      main: getRandomEnvIndex(assets.main.length),
      detail: getRandomEnvIndex(assets.detail.length),
      shadow: 1,
    });
  };

  const handleSendToEditor = () => {
    onGenerate(formatXml(previewSvg));
  };

  const changePart = (category: EnvironmentCategory, direction: -1 | 1) => {
    setConfig(prev => {
      const max = assets[category].length;
      let next = prev[category] + direction;
      if (next < 0) next = max - 1;
      if (next >= max) next = 0;
      return { ...prev, [category]: next };
    });
  };

  const categories: { key: EnvironmentCategory; label: string }[] = [
    { key: 'main', label: 'Object / Tree / Rock' },
    { key: 'detail', label: 'Details / Flowers' },
    { key: 'ground', label: 'Ground Base' },
    { key: 'shadow', label: 'Shadow Type' },
  ];

  return (
    <div className="w-full h-full flex flex-col md:flex-row bg-gray-900 text-white overflow-hidden">
      {/* Left: Preview Area */}
      <div className="w-full md:w-1/2 h-1/2 md:h-full flex flex-col items-center justify-center p-8 bg-gray-900 border-b md:border-b-0 md:border-r border-gray-800 relative">
        <div className="absolute top-4 left-4 z-10">
             <div className="bg-green-900/50 backdrop-blur px-3 py-1 rounded-full text-xs font-semibold text-green-200 border border-green-700">
                Nature & Props
             </div>
        </div>

        <div className="relative group">
            <div className="w-[300px] h-[300px] md:w-[400px] md:h-[400px] bg-checkerboard rounded-xl shadow-2xl overflow-hidden border-4 border-gray-700 relative">
                <div 
                    className="w-full h-full transform transition-transform duration-300 hover:scale-105"
                    dangerouslySetInnerHTML={{ __html: previewSvg }} 
                />
                 {/* Center Crosshair for Alignment Reference */}
                 <div className="absolute inset-0 pointer-events-none opacity-20 flex items-center justify-center">
                    <div className="w-full h-px bg-green-500 absolute"></div>
                    <div className="h-full w-px bg-green-500 absolute"></div>
                </div>
            </div>
            <div className="absolute -bottom-14 w-full flex justify-center">
                 <button 
                    onClick={handleRandomize}
                    className="flex items-center space-x-2 px-6 py-2.5 bg-gray-700 hover:bg-gray-600 rounded-full transition-all shadow-lg text-sm font-bold border border-gray-600"
                 >
                    <Dice5 size={18} className="text-green-400" />
                    <span>Randomize</span>
                 </button>
            </div>
        </div>
      </div>

      {/* Right: Controls */}
      <div className="w-full md:w-1/2 h-1/2 md:h-full bg-gray-800 flex flex-col border-l border-gray-700">
         <div className="p-5 border-b border-gray-700 flex justify-between items-center bg-gray-800 z-10 shadow-sm">
            <h2 className="text-lg font-bold text-green-400">Environment Config</h2>
         </div>

         <div className="flex-1 overflow-y-auto p-6 scrollbar-thin">
            <div className="space-y-3">
                {categories.map((cat) => (
                    <div key={cat.key} className="bg-gray-900/40 p-1 rounded-xl border border-gray-700/50 hover:border-green-900/50 transition-colors">
                        <div className="flex items-center">
                             <div className="flex flex-col justify-center items-center w-12 h-14 border-r border-gray-700/50 text-gray-500">
                                <span className="text-[10px] font-bold uppercase rotate-180 writing-vertical-lr">{config[cat.key] + 1}/{assets[cat.key].length}</span>
                            </div>

                            <div className="flex-1 px-4 py-2">
                                <div className="text-[10px] font-bold text-gray-500 uppercase tracking-wider mb-0.5">{cat.label}</div>
                                <div className="text-sm font-medium text-white truncate">
                                    {assets[cat.key][config[cat.key]]?.name || 'Unknown'}
                                </div>
                            </div>
                            
                            <div className="flex space-x-1 pr-2">
                                <button 
                                    onClick={() => changePart(cat.key, -1)}
                                    className="p-2 hover:bg-gray-700 rounded-lg text-gray-400 hover:text-white transition-colors"
                                >
                                    <ChevronLeft size={18} />
                                </button>
                                <button 
                                    onClick={() => changePart(cat.key, 1)}
                                    className="p-2 hover:bg-gray-700 rounded-lg text-gray-400 hover:text-white transition-colors"
                                >
                                    <ChevronRight size={18} />
                                </button>
                            </div>
                        </div>
                    </div>
                ))}
            </div>
         </div>

         <div className="p-6 border-t border-gray-700 bg-gray-800">
            <button 
                    onClick={handleSendToEditor}
                    className="w-full flex items-center justify-center space-x-2 bg-gradient-to-r from-green-600 to-emerald-600 hover:from-green-500 hover:to-emerald-500 text-white px-6 py-4 rounded-xl font-bold shadow-lg shadow-green-900/20 transition-all transform hover:translate-y-[-1px]"
                >
                    <span>Export to Editor</span>
                    <ArrowRight size={18} />
            </button>
         </div>
      </div>
    </div>
  );
};

export default EnvironmentConstructor;