import React, { useState, useEffect } from 'react';
import { ArrowRight, Dice5, ChevronLeft, ChevronRight, Plus, Save, Trash2 } from 'lucide-react';
import { INITIAL_STRUCTURE_ASSETS, getRandomStructureIndex, StructureCategory, StructurePart } from '../structureAssets';
import { formatXml } from '../utils/formatUtils';

interface StructureConstructorProps {
  onGenerate: (svgCode: string) => void;
}

const StructureConstructor: React.FC<StructureConstructorProps> = ({ onGenerate }) => {
  const [assets, setAssets] = useState(INITIAL_STRUCTURE_ASSETS);
  
  const [config, setConfig] = useState<Record<StructureCategory, number>>({
    ground: 0,
    foundation: 0,
    walls: 0,
    roof: 0,
    entrance: 0,
    decor: 0,
  });

  const [previewSvg, setPreviewSvg] = useState('');
  const [isCreatorMode, setIsCreatorMode] = useState(false);
  
  const [newAssetCategory, setNewAssetCategory] = useState<StructureCategory>('roof');
  const [newAssetName, setNewAssetName] = useState('');
  const [newAssetSvg, setNewAssetSvg] = useState('');

  // Load custom assets on mount
  useEffect(() => {
    const saved = localStorage.getItem('svgStudio_structureAssets');
    if (saved) {
      try {
        const customParts = JSON.parse(saved);
        setAssets(prev => {
          const merged = { ...prev };
          Object.keys(customParts).forEach(key => {
            const k = key as StructureCategory;
            if (merged[k]) {
              merged[k] = [...merged[k], ...customParts[k]];
            }
          });
          return merged;
        });
      } catch (e) {
        console.error("Failed to load custom structure assets", e);
      }
    }
  }, []);

  useEffect(() => {
    setPreviewSvg(buildSvg());
  }, [config, assets]);

  const buildSvg = () => {
    const getPart = (key: StructureCategory) => assets[key][config[key]] || assets[key][0];

    const ground = getPart('ground');
    const foundation = getPart('foundation');
    const walls = getPart('walls');
    const roof = getPart('roof');
    const entrance = getPart('entrance');
    const decor = getPart('decor');

    // Increased ViewBox to -50 -50 300 300
    return `<svg width="200" height="200" viewBox="-50 -50 300 300" xmlns="http://www.w3.org/2000/svg">
  <!-- Top-Down Structure Generated by SVG Studio Pro -->
  <defs>
    <filter id="bldgShadow" x="-20%" y="-20%" width="140%" height="140%">
      <feGaussianBlur in="SourceAlpha" stdDeviation="3"/>
      <feOffset dx="3" dy="4" result="offsetblur"/>
      <feComponentTransfer>
        <feFuncA type="linear" slope="0.4"/>
      </feComponentTransfer>
      <feMerge> 
        <feMergeNode/>
        <feMergeNode in="SourceGraphic"/> 
      </feMerge>
    </filter>
  </defs>

  <g id="ground">${ground.svg}</g>
  
  <g id="building" filter="url(#bldgShadow)">
    <g id="foundation">${foundation.svg}</g>
    <g id="walls">${walls.svg}</g>
    <g id="entrance">${entrance.svg}</g>
    <g id="roof">${roof.svg}</g>
    <g id="decor">${decor.svg}</g>
  </g>
</svg>`;
  };

  const handleRandomize = () => {
    setConfig({
      ground: getRandomStructureIndex(assets.ground.length),
      foundation: getRandomStructureIndex(assets.foundation.length),
      walls: getRandomStructureIndex(assets.walls.length),
      roof: getRandomStructureIndex(assets.roof.length),
      entrance: getRandomStructureIndex(assets.entrance.length),
      decor: getRandomStructureIndex(assets.decor.length),
    });
  };

  const handleSendToEditor = () => {
    onGenerate(formatXml(previewSvg));
  };

  const changePart = (category: StructureCategory, direction: -1 | 1) => {
    setConfig(prev => {
      const max = assets[category].length;
      let next = prev[category] + direction;
      if (next < 0) next = max - 1;
      if (next >= max) next = 0;
      return { ...prev, [category]: next };
    });
  };

  const handleAddAsset = () => {
    if (!newAssetName || !newAssetSvg) return;

    const newPart: StructurePart = {
      id: `custom_s_${Date.now()}`,
      name: newAssetName,
      svg: newAssetSvg,
      category: newAssetCategory
    };

    setAssets(prev => ({
      ...prev,
      [newAssetCategory]: [...prev[newAssetCategory], newPart]
    }));

    const existing = localStorage.getItem('svgStudio_structureAssets');
    const storageObj = existing ? JSON.parse(existing) : {};
    if (!storageObj[newAssetCategory]) storageObj[newAssetCategory] = [];
    storageObj[newAssetCategory].push(newPart);
    localStorage.setItem('svgStudio_structureAssets', JSON.stringify(storageObj));

    setNewAssetName('');
    setNewAssetSvg('');
    setConfig(prev => ({
      ...prev,
      [newAssetCategory]: assets[newAssetCategory].length
    }));
    
    alert(`Added ${newAssetName}!`);
  };

  const handleClearCustomAssets = () => {
    if(confirm("Delete all custom structure assets?")) {
      localStorage.removeItem('svgStudio_structureAssets');
      setAssets(INITIAL_STRUCTURE_ASSETS);
      setConfig({ ground:0, foundation:0, walls:0, roof:0, entrance:0, decor:0 });
    }
  };

  const categories: { key: StructureCategory; label: string }[] = [
    { key: 'roof', label: 'Roof Style' },
    { key: 'walls', label: 'Walls / Structure' },
    { key: 'entrance', label: 'Entrance / Door' },
    { key: 'decor', label: 'Decor / Addons' },
    { key: 'foundation', label: 'Foundation' },
    { key: 'ground', label: 'Ground Environment' },
  ];

  return (
    <div className="w-full h-full flex flex-col md:flex-row bg-gray-900 text-white overflow-hidden">
      {/* Left: Preview Area */}
      <div className="w-full md:w-1/2 h-1/2 md:h-full flex flex-col items-center justify-center p-8 bg-gray-900 border-b md:border-b-0 md:border-r border-gray-800 relative">
        <div className="absolute top-4 left-4 z-10">
             <div className="bg-gray-800/80 backdrop-blur px-3 py-1 rounded-full text-xs font-semibold text-gray-400 border border-gray-700">
                Top-Down Structures
             </div>
        </div>

        <div className="relative group">
            <div className="w-[300px] h-[300px] md:w-[400px] md:h-[400px] bg-checkerboard rounded-xl shadow-2xl overflow-hidden border-4 border-gray-700 relative">
                <div 
                    className="w-full h-full transform transition-transform duration-300 hover:scale-105"
                    dangerouslySetInnerHTML={{ __html: previewSvg }} 
                />
                 <div className="absolute inset-0 pointer-events-none opacity-20 flex items-center justify-center">
                    <div className="w-full h-px bg-blue-500 absolute"></div>
                    <div className="h-full w-px bg-blue-500 absolute"></div>
                </div>
            </div>
            <div className="absolute -bottom-14 w-full flex justify-center">
                 <button 
                    onClick={handleRandomize}
                    className="flex items-center space-x-2 px-6 py-2.5 bg-gray-700 hover:bg-gray-600 rounded-full transition-all shadow-lg text-sm font-bold border border-gray-600"
                 >
                    <Dice5 size={18} />
                    <span>Randomize</span>
                 </button>
            </div>
        </div>
      </div>

      {/* Right: Controls */}
      <div className="w-full md:w-1/2 h-1/2 md:h-full bg-gray-800 flex flex-col border-l border-gray-700">
         <div className="p-5 border-b border-gray-700 flex justify-between items-center bg-gray-800 z-10 shadow-sm">
            <h2 className="text-lg font-bold text-white flex items-center gap-2">Building Config</h2>
            <button 
                onClick={() => setIsCreatorMode(!isCreatorMode)}
                className={`flex items-center space-x-1 px-3 py-1.5 rounded-full text-xs font-bold transition-all border ${isCreatorMode ? 'bg-violet-600 border-violet-500 text-white' : 'bg-transparent border-gray-600 text-gray-400 hover:border-gray-400 hover:text-white'}`}
            >
                <Plus size={14} />
                <span>Custom Part</span>
            </button>
         </div>

         <div className="flex-1 overflow-y-auto p-6 scrollbar-thin">
            {isCreatorMode && (
                <div className="mb-6 bg-gray-900/50 border border-violet-500/30 rounded-xl p-5">
                    <h3 className="font-bold text-violet-400 mb-4 text-sm uppercase tracking-wide">Add Structure Asset</h3>
                    <div className="space-y-4">
                        <div className="grid grid-cols-2 gap-4">
                            <div>
                                <label className="block text-[10px] text-gray-500 uppercase font-bold mb-1">Category</label>
                                <select 
                                    value={newAssetCategory}
                                    onChange={(e) => setNewAssetCategory(e.target.value as StructureCategory)}
                                    className="w-full bg-gray-800 border border-gray-600 rounded-lg px-3 py-2 text-sm focus:border-violet-500 outline-none"
                                >
                                    {categories.map(c => <option key={c.key} value={c.key}>{c.label}</option>)}
                                </select>
                            </div>
                            <div>
                                <label className="block text-[10px] text-gray-500 uppercase font-bold mb-1">Name</label>
                                <input 
                                    type="text"
                                    value={newAssetName}
                                    onChange={(e) => setNewAssetName(e.target.value)}
                                    placeholder="e.g., Solar Panel"
                                    className="w-full bg-gray-800 border border-gray-600 rounded-lg px-3 py-2 text-sm focus:border-violet-500 outline-none"
                                />
                            </div>
                        </div>
                        <div>
                            <label className="block text-[10px] text-gray-500 uppercase font-bold mb-1">SVG Code</label>
                            <textarea 
                                value={newAssetSvg}
                                onChange={(e) => setNewAssetSvg(e.target.value)}
                                placeholder={'<rect width="10" height="10" fill="blue" />'}
                                className="w-full h-20 bg-gray-800 border border-gray-600 rounded-lg px-3 py-2 text-xs font-mono focus:border-violet-500 outline-none resize-none"
                            />
                        </div>
                        <div className="flex justify-end pt-2">
                            <button 
                                onClick={handleAddAsset}
                                disabled={!newAssetName || !newAssetSvg}
                                className="bg-violet-600 hover:bg-violet-500 text-white px-5 py-2 rounded-lg text-sm font-bold shadow-md disabled:opacity-50 flex items-center gap-2"
                            >
                                <Save size={16} /> Save
                            </button>
                        </div>
                    </div>
                </div>
            )}

            <div className="space-y-3">
                {categories.map((cat) => (
                    <div key={cat.key} className="bg-gray-900/40 p-1 rounded-xl border border-gray-700/50 hover:border-gray-600 transition-colors">
                        <div className="flex items-center">
                            <div className="flex flex-col justify-center items-center w-12 h-14 border-r border-gray-700/50 text-gray-500">
                                <span className="text-[10px] font-bold uppercase rotate-180 writing-vertical-lr">{config[cat.key] + 1}/{assets[cat.key].length}</span>
                            </div>

                            <div className="flex-1 px-4 py-2">
                                <label className="text-[10px] font-bold text-gray-500 uppercase tracking-wider mb-0.5">{cat.label}</label>
                                <span className="block text-sm font-medium text-white truncate">
                                    {assets[cat.key][config[cat.key]]?.name || 'Unknown'}
                                </span>
                            </div>

                            <div className="flex space-x-1 pr-2">
                                <button 
                                    onClick={() => changePart(cat.key, -1)}
                                    className="p-2 hover:bg-gray-700 rounded-lg text-gray-400 hover:text-white transition-colors"
                                >
                                    <ChevronLeft size={18} />
                                </button>
                                
                                <button 
                                    onClick={() => changePart(cat.key, 1)}
                                    className="p-2 hover:bg-gray-700 rounded-lg text-gray-400 hover:text-white transition-colors"
                                >
                                    <ChevronRight size={18} />
                                </button>
                            </div>
                        </div>
                    </div>
                ))}
            </div>
         </div>

         <div className="p-6 border-t border-gray-700 bg-gray-800">
            <button 
                    onClick={handleSendToEditor}
                    className="w-full flex items-center justify-center space-x-2 bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-500 hover:to-indigo-500 text-white px-6 py-4 rounded-xl font-bold shadow-lg shadow-violet-900/20 transition-all transform hover:translate-y-[-1px]"
                >
                    <span>Export to Editor</span>
                    <ArrowRight size={18} />
            </button>
         </div>
      </div>
    </div>
  );
};

export default StructureConstructor;